'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class fueltaxEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=fueltaxEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property gasolinegbycous() As DbSet(Of gasolinegbycou)
    Public Overridable Property gasrevperyears() As DbSet(Of gasrevperyear)
    Public Overridable Property gasrevperyearscen1() As DbSet(Of gasrevperyearscen1)
    Public Overridable Property gasrevperyearscen2() As DbSet(Of gasrevperyearscen2)
    Public Overridable Property gasrevperyearscen3() As DbSet(Of gasrevperyearscen3)
    Public Overridable Property gasrevperyearscen4() As DbSet(Of gasrevperyearscen4)
    Public Overridable Property gasrevperyearscen5() As DbSet(Of gasrevperyearscen5)
    Public Overridable Property gasrevtohwyfnds() As DbSet(Of gasrevtohwyfnd)
    Public Overridable Property gasvsgasoholes() As DbSet(Of gasvsgasohole)
    Public Overridable Property mcspefuels() As DbSet(Of mcspefuel)
    Public Overridable Property news() As DbSet(Of news)
    Public Overridable Property taxcollgalls() As DbSet(Of taxcollgall)
    Public Overridable Property taxcolmoneys() As DbSet(Of taxcolmoney)
    Public Overridable Property taxcolmoney2() As DbSet(Of taxcolmoney2)
    Public Overridable Property accessrights() As DbSet(Of accessright)

End Class
