'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class gasvsgasohole
    Public Property ID As Integer
    Public Property year As Integer
    Public Property gasoline As Integer
    Public Property gasohole As Integer
    Public Property total As Integer

End Class
