'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class taxcollgall
    Public Property ID As Integer
    Public Property year As Integer
    Public Property month As String
    Public Property CountyN As String
    Public Property Diesel As Integer
    Public Property CNG As Integer
    Public Property LPG As Integer
    Public Property A55 As Integer

End Class
